<div class="page-header">
	<h3>
		<?php echo $this->translate('Cadastro de Usuários'); ?>
	</h3>
</div>
<div class="row">
	<div class="col-md-3">
		<a class="btn btn-info" href="<?php echo $this->url('dsl-power-users', array('action' => 'new')); ?>">
			<span class="glyphicon glyphicon-plus"></span>
			<?php echo $this->translate('Novo Usuário'); ?>
		</a>
	</div>
	<div class="col-md-9">
		<form class="form-inline" role="form" method="post">
			<div class="form-group">
				<label class="sr-only" for="searchTerm">
					<?php echo $this->translate('Search'); ?>
				</label>
				<input type="text" class="form-control" id="searchTerm" value="<?php echo $searchTerm; ?>" placeholder="<?php echo $this->translate("Nome"); ?>" name="searchTerm" />
			</div>
			<button type="submit" class="btn btn-default">
				<span class="glyphicon glyphicon-search"></span>
				<?php echo $this->translate('Pesquisa'); ?>
			</button>
		</form>
	</div>
</div>
<br />

<table class="table table-hover table-responsive table-striped">
	<thead>
		<tr>
			<th>
				<?php echo $this->translate('Nome'); ?>
			</th>
			<th>
				<?php echo $this->translate('Nome de Usuário'); ?>
			</th>
			<th>
				<?php echo $this->translate('Email'); ?>
			</th>
			<th>
				<?php echo $this->translate('Editar'); ?>
			</th>
			<th>
				<?php echo $this->translate('Remove'); ?>
			</th>
		</tr>
	</thead>
	<tbody>
		
	</tbody>
</table>