<?php 
$form = $this->loginForm;
$form->add(array(
	'name' => 'login',
	'type' => 'submit',
	'attributes' => array(
		'value' => 'Fazer Login',
		'class' => 'btn btn-lg btn-primary btn-block',
	)
));
$form->prepare();
$form->get('identity')->setAttributes(array('class' => 'form-control', 'placeholder' => 'exemplo@gmail.com'));
$form->get('credential')->setAttributes(array('class' => 'form-control', 'placeholder' => 'Senha'));
?>
<div class="container" style="margin-top: 40px;">
	<div class="row">
		<div class="col-sm-6 col-md-4 col-md-offset-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<strong>Entre para continuar</strong>
				</div>
				<div class="panel-body">
					<?php echo $this->form()->openTag($form); ?>
						<filedset>
							<div class="row">
								<div class="center-block">
									<img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120" alt="" />
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12 col-md-10 col-md-offset-1">
									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">
												<i class="glyphicon glyphicon-user"></i>
											</span>
											<?php echo $this->formElement($form->get('identity')); ?>
										</div>
									</div>
									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">
												<i class="glyphicon glyphicon-lock"></i>
											</span>
											<?php echo $this->formElement($form->get('credential')); ?>
										</div>
									</div>
									<div class="form-group">
										<?php echo $this->formElement($form->get('login')); ?>
									</div>
								</div>
							</div>
						</filedset>
					<?php echo $this->form()->closeTag(); ?>
				</div>
				<div class="panel-footer">
					Não tem uma conta! <a href="#">Inscreva-se aqui</a>
				</div>
			</div>
		</div>
	</div>
</div>